---
# handlers file for setup-apache
- name: start the services
  service:
    name: apache2
    state: started

- name: restart apache
  service:
    name: httpd
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted

